- name: Update and Upgrade
  hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

- name: Setup Utilities
  hosts: localhost
  connection: local
  roles: ['openvpn', 'python3', 'python2', 'docker', 'docker-compose', 'proxychains', '7zip', 'firefox-extensions', 'passiverecon-tools', 'activerecon-tools', 'win_bins', 'cyberchef', 'binwalk']

- name: Setup Editors
  hosts: localhost
  connection: local
  roles: ['vscode', 'editor_cherrytree']

- name: Setup Network tools
  hosts: localhost
  connection: local
  roles: ['wireshark']

- name: Setup Discovery tools
  hosts: localhost
  connection: local
  roles: ['nmap', 'ffuf', 'dirb', 'gobuster', 'ansible-role-burpsuite', 'masscan']
  pre_tasks:
   - set_fact:
       burpsuite_user: "{{ ansible_user }}"

- name: Setup Service Enumeration tools
  hosts: localhost
  connection: local
  roles: ['enum4linux-ng']

- name: Setup Exploit tools
  hosts: localhost
  connection: local
  roles: ['metasploit', 'empiresuite']

- name: Setup Password Crackering tools
  hosts: localhost
  connection: local
  roles: ['hydra']

- name: Setup Data Sources
  hosts: localhost
  connection: local
  roles: ['data_source-SecLists', 'data_source-reverse-shells']

- name: Ubuntu optimization
  hosts: localhost
  connection: local
  tasks:
  - name: Cleanup old kernels
    become: true
    shell:
      cmd: "dpkg -l linux-{image,headers}-* | awk '/^ii/{print $2}' | egrep '[0-9]+\\.[0-9]+\\.[0-9]+' | grep -v $(uname -r) | xargs apt-get -y purge"

  - name: Remove amazon search results from the dash
    become: true
    apt:
      pkg:
        - ubuntu-web-launchers
      state: absent

  - name: Disable error reporting
    become: true
    apt:
      pkg:
        - whoopsie
        - apport
        - apport-gtk
      state: absent

  - name: Prevent usage statistics to being sent to Canonical
    dconf:
      key: "/org/gnome/desktop/privacy/send-software-usage-stats"
      value: "false"
      state: present

  - name: Prevent technical problem statistics to being sent to Canonical
    dconf:
      key: "/org/gnome/desktop/privacy/report-technical-problem"
      value: "false"
      state: present

  - name: Clean up packages
    become: true
    apt:
      autoremove: true

- name: Customize Gnome
  hosts: localhost
  connection: local
  roles:
    - role: petermosmans.customize-gnome
  vars:
    gnome_dconf:
    gnome_extensions:
      - id: 3612 # WireGuard Indicator
    gnome_user: "{{ ansible_user_id }}"

# - name: VPN Killswtich
#   hosts: localhost
#   connection: local
#   tasks:
#   - name: Install IPtables-persistent
#     become: true
#     apt:
#       name:
#         - iptables-persistent
#       update_cache: yes
#       state: present
#   - name: Disallow all traffic
#     become: true
#     iptables:
#       chain: INPUT
#       jump: DROP
#   - name: Disallow all traffic
#     become: true
#     iptables:
#       chain: FORWARD
#       jump: DROP
#   - name: Disallow all traffic
#     become: true
#     iptables:
#       chain: OUTPUT
#       jump: DROP
#   - name: Allow Loopback and Ping
#     become: true
#     iptables:
#       chain: INPUT
#       in_interface: lo
#       jump: ACCEPT
#   - name: Allow Loopback and Ping
#     become: true
#     iptables:
#       chain: INPUT
#       out_interface : lo
#       jump: ACCEPT
#   - name: Allow Loopback and Ping
#     become: true
#     iptables:
#       chain: OUTPUT
#       out_interface : tun0
#       jump: ACCEPT
#   - name: Allow DHCP server
#     become: true
#     iptables:
#       chain: OUTPUT
#       destination: 255.255.255.255
#       jump: ACCEPT
#   - name: Allow DHCP server
#     become: true
#     iptables:
#       INPUT: OUTPUT
#       source: 255.255.255.255
#       jump: ACCEPT
#   - name: Allow Local/LAN network
#     become: true
#     iptables:
#       INPUT: INPUT
#       source: 192.168.1.0/24
#       destination: 196.168.1.0/24
#       jump: ACCEPT
#   - name: Allow Local/LAN network
#     become: true
#     iptables:
#       INPUT: OUTPUT
#       source: 192.168.1.0/24
#       destination: 196.168.1.0/24
#       jump: ACCEPT
#   - name: Allow established sessions
#     become: true
#     iptables:
#       INPUT: INPUT
#       ctstate: ESTABLISHED,RELATED
#       jump: ACCEPT
#   - name: Allow DNS
#     become: true
#     iptables:
#       chain: OUTPUT
#       destination: "{{vpn_ip}}"
#       jump: ACCEPT
#   - name: Allow VPN
#     become: true
#     iptables:
#       chain: OUTPUT
#       destination: "{{vpn_ip}}"
#       protocol: udp
#       destination_ports:
#         - 1194
#         - 53
#       out_interface: eth*
#       jump: ACCEPT
#   connection: local
#   tasks:
#   - name: Drop IPv6
#     become: true
#     iptables:
#       ip_version: "ipv6"
#       chain: INPUT
#       jump: DROP
#   - name: Drop IPv6
#     become: true
#     iptables:
#       ip_version: "ipv6"
#       chain: FORWARD
#       jump: DROP
#   - name: Drop IPv6
#     become: true
#     iptables:
#       ip_version: "ipv6"
#       chain: OUTPUT
#       jump: DROP
#   - name: Save iptables
#     become: true
#     shell: iptables-save > /etc/iptables/rules.v4
