- name: Network configuration with VPN Killswtich
  hosts: localhost
  connection: local
  vars:
    - ethernet_interface:
      - conn_name: "ens33"
        range4: "192.168.255.0/24"
        ip4: "192.168.255.50/24"
        gw4: "192.168.255.2"
        dns4: "8.8.8.8"
      - conn_name: "ens34"
        range4: "172.16.6.0/24"
        ip4: "172.16.6.50/24"
        gw4: ""
        dns4: ""
    - vpn_ip: ""
  tasks:
  - name: Configure Ethernet interface
    become: true
    nmcli:
      conn_name: '{{ item.conn_name }}'
      type: ethernet
      ip4: '{{ item.ip4 }}'
      gw4: '{{ item.gw4 }}'
      dns4: '{{ item.dns4 }}'
      state: present
    loop: '{{ ethernet_interface }}'
  - name: Remove /etc/resolv.conf
    become: true
    file:
      path: /etc/resolv.conf
      state: absent
  - name: Set new static /etc/resolv.conf
    become: true
    template:
      src: resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root
  - name: Install IPtables-persistent
    become: true
    apt:
      name:
        - iptables-persistent
      state: present
  - name: Clear iptables
    become: true
    iptables:
      chain: "{{ item }}"
      flush: yes
    with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]
  - name: Disallow all traffic (INPUT chain)
    become: true
    iptables:
      chain: INPUT
      jump: DROP
      action: "insert"
  - name: Disallow all traffic (FORWARD chain)
    become: true
    iptables:
      chain: FORWARD
      jump: DROP
      action: "insert"
  - name: Disallow all traffic
    become: true
    iptables:
      chain: OUTPUT
      jump: DROP
      action: "insert"
  - name: Restart docker (to restore docker rules)
    become: true
    systemd:
      name: docker
      state: restarted
  - name: Allow Loopback and Ping (OUTPUT)
    become: true
    iptables:
      chain: OUTPUT
      out_interface : lo
      jump: ACCEPT
      action: "insert"
  - name: Allow VPN tunnel traffic
    become: true
    iptables:
      chain: OUTPUT
      out_interface : tun0
      jump: ACCEPT
      action: "insert"
  - name: Allow DHCP server (destination)
    become: true
    iptables:
      chain: OUTPUT
      destination: 255.255.255.255
      jump: ACCEPT
      action: "insert"
  - name: Allow DHCP server (source)
    become: true
    iptables:
      chain: OUTPUT
      source: 255.255.255.255
      jump: ACCEPT
      action: "insert"
  - name: Allow Local/LAN network
    become: true
    iptables:
      chain: INPUT
      source: "{{ item.range4 }}"
      destination: "{{ item.range4 }}"
      jump: ACCEPT
      action: "insert"
    loop: '{{ ethernet_interface }}'
  - name: Allow Local/LAN network
    become: true
    iptables:
      chain: OUTPUT
      source: "{{ item.range4 }}"
      destination: "{{ item.range4 }}"
      jump: ACCEPT
      action: "insert"
    loop: '{{ ethernet_interface }}'
  - name: Allow established sessions
    become: true
    iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT
      action: "insert"
  - name: Allow DNS
    become: true
    iptables:
      chain: OUTPUT
      destination: "{{vpn_ip}}"
      jump: ACCEPT
      action: "insert"
  - name: Allow VPN
    become: true
    iptables:
      chain: OUTPUT
      destination: "{{vpn_ip}}"
      protocol: udp
      destination_ports:
        - 1194
        - 53
      out_interface: eth*
      jump: ACCEPT
      action: "insert"
  - name: Drop IPv6
    become: true
    iptables:
      ip_version: "ipv6"
      chain: INPUT
      jump: DROP
      action: "insert"
  - name: Drop IPv6
    become: true
    iptables:
      ip_version: "ipv6"
      chain: FORWARD
      jump: DROP
      action: "insert"
  - name: Drop IPv6
    become: true
    iptables:
      ip_version: "ipv6"
      chain: OUTPUT
      jump: DROP
      action: "insert"
  - name: Save iptables
    become: true
    shell: iptables-save > /etc/iptables/rules.v4
