- name: Network configuration with VPN Killswtich
  hosts: localhost
  connection: local
  vars:
    - internal_if: "ens34"
    - openvpn_ip: ""
    - openvpn_ca: ""
    - openvpn_cert: ""
    - openvpn_key: ""
    - openvpn_tls_auth: ""
  tasks:
  - name: Delete any old OpenVPN configurations (if they exist)
    become: true
    shell: "nmcli connection delete OpenVPN"
    ignore_errors: true
  - name: Deploy OpenVPN.ovpn
    become: true
    template:
      src: OpenVPN.ovpn.j2
      dest: '/etc/openvpn/OpenVPN.ovpn'
      owner: root
      group: root
  - name: Deploy up script
    become: true
    template:
      src: openvpn_up.sh.j2
      dest: '/etc/network/if-up.d/openvpn_up'
      owner: root
      group: root
      mode: '0700'
  - name: Deploy down script
    become: true
    template:
      src: openvpn_down.sh.j2
      dest: '/etc/network/if-down.d/openvpn_down'
      owner: root
      group: root
      mode: '0700'
  - name: Import OpenVPN.ovpn
    become: true
    shell: "nmcli connection import type openvpn file /etc/openvpn/OpenVPN.ovpn"
  # - name: Enable OpenVPN.ovpn on boot
  #   become: true
  #   shell: "nmcli connection modify OpenVPN connection.autoconnect yes"
  - name: Enable IP Forwarding
    become: true
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
