- name: Install Microsoft repository key
  become: yes
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: Setup VS Code repository
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/code stable main'
    filename: vscode
    state: present

- name: Install VS Code
  apt:
    name: vscode
    state: latest