- name: Install Microsoft repository key
  become: true
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: Setup VS Code repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/code stable main'
    filename: vscode
    state: present

- name: Install VS Code
  become: true
  apt:
    name: code
    state: latest

- name: Install VS Code Extensions
  shell: code --install-extension "{{ item }}"
  loop:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-vscode.cpptools
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - VisualStudioExptTeam.vscodeintellicode
    - redhat.vscode-yaml
    - ban.spellright
    - DavidAnson.vscode-markdownlint

- name: Setup VS Code config directory
  file:
    path: '~{{ ansible_user_id }}/.config/Code'
    state: directory
    mode: 0775

- name: Setup VS Code settings directory
  file:
    path: '~{{ ansible_user_id }}/.config/Code/User'
    state: directory
    mode: 0775

- name: Push default VS Code settings
  template:
    src: settings.json.j2
    dest: '~{{ ansible_user_id }}/.config/Code/User/settings.json'
    mode: 0664