- name: Install Microsoft repository key
  become: yes
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: Setup VS Code repository
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/code stable main'
    filename: vscode
    state: present

- name: Install VS Code
  apt:
    name: code
    state: latest

- name: Install VS Code Extensions
  shell: code --install-extension "{{ item }}"
  become: "{{ ansible_user_id }}"
  loop:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-vscode.cpptools
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - VisualStudioExptTeam.vscodeintellicode
    - redhat.vscode-yaml
