- name: FoxyProxy Basic
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3616827/foxyproxy_basic-7.5.1-an+fx.xpi
    dest: /tmp/foxyproxy_basic.xpi

- name: Install Extension
  shell: firefox -silent -install-global-extension /tmp/foxyproxy_basic.xpi