- name: Setup .mozilla folder
  file:
    path: '~/.mozilla'
    state: directory

- name: Setup Extensions folder
  file:
    path: '~/.mozilla/extensions'
    state: directory

- name: FoxyProxy Basic
  get_url:
    url: https://addons.mozilla.org/firefox/downloads/file/3616827/foxyproxy_basic-7.5.1-an+fx.xpi
    dest: ~/.mozilla/extensions/foxyproxy_basic.xpi