- name: Install Active Recon tools
  become: true
  apt:
    name:
    - traceroute
    - masscan
    state: latest

- name: Pull latest DNSRecon version
  become: true
  pip:
    name:
      - git+https://github.com/darkoperator/dnsrecon.git
    executable: pip3