- name: Download docker-compose binary
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0775'

- name: Create a symbolic link for docker-compose to /usr/bin/docker-compose
  become: true
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    owner: root
    group: root
    state: link

- name: Make sure python package docker-compose is present
  become: true
  pip:
    name: docker-compose
    state: present
    executable: pip3

