- name: Download installer
  become: true
  get_url:
    url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb
    dest: /tmp/msfinstall
    mode: 0755
  register: metasploit

- name: Install Metasploit
  when: metasploit.changed
  become: true
  command: /tmp/msfinstall
  
- name: Setup desktop shortcut folder
  file:
    path: '~{{ ansible_user_id }}/Desktop/ExploitTools/'
    state: directory

- name: Deploy desktop shortcut
  template:
    src: metasploit.desktop.j2
    dest: '~{{ ansible_user_id }}/Desktop/ExploitTools/metasploit.desktop'
    mode: 'a+x'

- name: Set the desktop shortcut as trusted
  shell: 'gio set ~{{ ansible_user_id }}/Desktop/ExploitTools/metasploit.desktop "metadata::trusted" yes'