- name: Fetch latest ffuf version
  uri:                                                               
    url: https://api.github.com/repos/ffuf/ffuf/releases/latest
    return_content: true                                             
  register: json_reponse                                             

- name: "Installing ffuf {{ json_reponse.json.tag_name }}"
  become: true
  loop: "{{ json_reponse.json.assets }}"
  when: "'linux_amd64.tar.gz' in item.name"
  unarchive:
    remote_src: true
    src: "{{ item.browser_download_url }}"
    dest: "/usr/local/bin/"
    mode: '0755'
    owner: root
    group: root

- name: Remove LICENSE file
  become: true
  file:
    src: /usr/local/bin/LICENSE
    state: absent

- name: Remove README.md file
  become: true
  file:
    src: /usr/local/bin/README.md
    state: absent

- name: Remove CHANGELOG.md file
  become: true
  file:
    src: /usr/local/bin/CHANGELOG.md
    state: absent

- name: Create a symbolic link for ffuf to /usr/bin/ffuf
  become: true
  file:
    src: /usr/local/bin/ffuf
    dest: /usr/bin/ffuf
    owner: root
    group: root
    state: link