- name: Setup Deadsnakes repository for Ubuntu Bionic
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'
  become: true
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'
    filename: deadsnakes_ppa
    state: present

- name: Install python3
  become: true
  apt:
    name: python3
    state: present

- name: Install python3-dev
  become: true
  apt:
    name: python3-dev
    state: present

- name: Set python3.8 as default for Ubuntu Bionic
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'
  become: true
  shell: update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1

- name: Fix apt_pkg issue for Ubuntu Bionic
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'
  become: true
  file:
    src: /usr/lib/python3/dist-packages/apt_pkg.cpython-36m-x86_64-linux-gnu.so
    dest: /usr/lib/python3/dist-packages/apt_pkg.cpython-38-x86_64-linux-gnu.so
    owner: root
    group: root
    state: link

- name: Get pip
  become: true
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Install pip3
  become: true
  shell: python3 /tmp/get-pip.py

- name: Install Common Python 3 packages
  become: true
  pip:
    name:
      - psutil
      - jmespath
    executable: pip3
