- name: Setup Cherrytree repository
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'
  become: true
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'
    filename: deadsnakes_ppa
    state: present

- name: Install python3
  become: true
  apt:
    name: python3
    state: present

- name: Install python3-dev
  become: true
  apt:
    name: python3-dev
    state: present

- name: Get pip
  become: true
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Install pip3
  become: true
  shell: python3 /tmp/get-pip.py

- name: Install Common Python 3 packages
  become: true
  pip:
    name:
      - psutil
      - jmespath
    executable: pip3
