- name: Fetch latest gobuster version
  uri:                                                               
    url: https://api.github.com/repos/OJ/gobuster/releases/latest
    return_content: true                                             
  register: json_reponse                                             

- name: "Download gobuster {{ json_reponse.json.tag_name }}"
  become: true
  loop: "{{ json_reponse.json.assets }}"
  when: "'Linux_x86_64.tar.gz' in item.name"
  unarchive:
    remote_src: true
    src: "{{ item.browser_download_url }}"
    dest: "/usr/local/bin/"
    mode: '0755'
    owner: root
    group: root   

- name: Create a symbolic link for gobuster to /usr/bin/gobuster
  become: true
  file:
    src: /usr/local/bin/gobuster
    dest: /usr/bin/gobuster
    owner: root
    group: root
    state: link

