- name: Install OpenVPN
  become: true
  apt:
    name:
    - openvpn
    - network-manager-openvpn
    state: latest

- name: Restart network manager
  service:
    name: network-manager
    state: restarted
  